### ISSUE TITLE
Add ERR message type

### ISSUE THREAD

**Issue by larsgk** [larsgk/web-broadcast-assistant#29]
Initially, it was seen as sufficient to have the three message types:

CMD - command sent to USB from Web
RES - immediate response from USB
EVT - async messages from USB (e.g. every time a device is found while scanning)

We *could* put OK/FAIL info in a RES payload, but maybe it makes more sense to use RES (possibly renamed to ACK?) for success and ERR for errors.  We then don't have to provide a reason in all cases and we also don't have to parse the payload every time to see if it went ok.

The sequence number (part of the message) can be used to connect commands to responses.

Success example
CMD - start scanning
RES - start scanning (nothing blocking)

Error example:
CMD - start scanning
ERR - already scanning

Thoughts?

**Comment by fredrikdanebjer** [comment]
>Error example:
CMD - start scanning
ERR - already scanning

I think that there are a lot of errors we can just discard, this being one of them. `already scanning` can from higher level also be seen as a success, in the sense that we will stand in the desired state after this command even if `already scanning` semantically is an `ERR`.

Beside that I agree with your reasoning, I think that it is a good idea to separate them as ACK and ERR to avoid unnecessary parsing. I think that there is a whole lot of cases where we simply do not care about the particular error

**Comment by smaerup** [comment]
What about errors happening asynchronously?
If a link loss occurs in situations where the webapp expects to be connected, we need some way of signalling this.
Maybe it then makes more sense to have a fixed error/status field in both RES and EVT messages.

**Comment by larsgk** [comment]
We decided to just add an error code field
